# -*- coding: utf-8 -*-
"""Q1_Fitting_sinx_curve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gorejaZB8XjA5hUln8-jLfYNmAt1_pm4

# Deep Learning Project - 1
Group - 7
* Kanishk Singh - SE21UCAM005
* Sanyam Agrawal - SE21UCSE192
* Shuvang Mishra - SE21UCSE209

# Building an ANN using Backpropagation and experimenting with multiple tools

## Q1. Fitting Sin(x) Function

### 1.1 Visualising Data - Sin(x)
"""

# Required Libraries
import numpy as np
import matplotlib.pyplot as plt

# common symbols and functions for ease of use
pi = np.pi
sin = np.sin

# Setting up data
x = np.linspace(-2*pi, 2*pi, 1000)
y = np.sin(x)

# Plotting data
plt.figure(figsize=(10,7))
plt.plot(x,y)
plt.title("Data")
plt.xlabel("x")
plt.ylabel("sin(x)")

"""### 1.2 Building our ANN class from scratch
1. Basic ANN: Implements a simple Artificial Neural Network with one hidden layer.
2. Flexible Activation: Supports various activation functions like relu, sigmoid, tanh, and linear.
3. Layer-wise Structure: Organizes layers with input sizes, output sizes, and activation functions.
4. Parameter Initialization: Uses appropriate initialization methods (He or Xavier) based on activation functions.
5. Forward and Backward Propagation: Efficiently calculates activations and gradients through the network.
6. Loss Calculation: Computes the mean squared error (MSE) loss between predicted and true outputs.
7. Parameter Update: Modifies weights and biases using gradients and a learning rate.
8. Training and Prediction: Provides methods for training the network on data and making predictions on new inputs.
"""

class ANN_1:
    def __init__(self):
        self.layers = []
        self.params = {}
        self.cache = {}
        self.grads = {}

    def add_layer(self, input_size, output_size, activation='relu'):
        layer_num = len(self.layers) + 1

        if activation == 'relu':
            # He Initialization
            std = np.sqrt(2. / input_size)
        elif activation in ['sigmoid', 'tanh']:
            # Xavier Initialization
            std = np.sqrt(1. / input_size)
        elif activation == 'linear':
            std = np.sqrt(1. / input_size)  # Similar to Xavier
        else:
            raise Exception(f"Unsupported activation: {activation}")

        self.params[f'W{layer_num}'] = np.random.randn(output_size, input_size) * std
        self.params[f'b{layer_num}'] = np.zeros((output_size, 1))
        self.layers.append({
            'input_size': input_size,
            'output_size': output_size,
            'activation': activation
        })

    def relu(self, Z):
        return np.maximum(0, Z)

    def relu_derivative(self, Z):
        return (Z > 0).astype(float)

    def sigmoid(self, Z):
        return 1 / (1 + np.exp(-Z))

    def sigmoid_derivative(self, Z):
        sig = self.sigmoid(Z)
        return sig * (1 - sig)

    def tanh(self, Z):
      return np.tanh(Z)

    def tanh_derivative(self, Z):
      return 1 - np.tanh(Z) ** 2

    def forward(self, X):
        A = X
        self.cache['A0'] = X

        for i, layer in enumerate(self.layers):
            layer_num = i + 1
            W = self.params[f'W{layer_num}']
            b = self.params[f'b{layer_num}']
            Z = np.dot(W, A) + b
            self.cache[f'Z{layer_num}'] = Z

            if layer['activation'] == 'relu':
                A = self.relu(Z)
            elif layer['activation'] == 'sigmoid':
                A = self.sigmoid(Z)
            elif layer['activation'] == 'linear':
                A = Z
            elif layer['activation'] == 'tanh':
                A = self.tanh(Z)
            else:
                raise Exception(f"Unsupported activation: {layer['activation']}")

            self.cache[f'A{layer_num}'] = A

        return A

    def compute_loss(self, Y_pred, Y_true):
        m = Y_true.shape[1]
        loss = (1 / (2 * m)) * np.sum((Y_pred - Y_true) ** 2)
        return loss

    def backward(self, Y_true):
        m = Y_true.shape[1]
        L = len(self.layers)
        Y_pred = self.cache[f'A{L}']

        # Initialize the gradient
        dA = Y_pred - Y_true  # Derivative of MSE loss with respect to A_L

        for i in reversed(range(1, L + 1)):
            Z = self.cache[f'Z{i}']
            A_prev = self.cache[f'A{i-1}']
            W = self.params[f'W{i}']

            layer = self.layers[i-1]
            activation = layer['activation']

            if activation == 'relu':
                dZ = dA * self.relu_derivative(Z)
            elif activation == 'sigmoid':
                dZ = dA * self.sigmoid_derivative(Z)
            elif activation == 'linear':
                dZ = dA  # Derivative of linear activation is 1
            elif activation == 'tanh':
                dZ = dA * self.tanh_derivative(Z)
            else:
                raise Exception(f"Unsupported activation: {activation}")

            dW = (1 / m) * np.dot(dZ, A_prev.T)
            db = (1 / m) * np.sum(dZ, axis=1, keepdims=True)
            dA = np.dot(W.T, dZ)

            self.grads[f'dW{i}'] = dW
            self.grads[f'db{i}'] = db

    def update_parameters(self, learning_rate=0.01):
        L = len(self.layers)
        for i in range(1, L + 1):
            self.params[f'W{i}'] -= learning_rate * self.grads[f'dW{i}']
            self.params[f'b{i}'] -= learning_rate * self.grads[f'db{i}']

    def train(self, X, Y, epochs=10000, learning_rate=0.01, print_loss=True):
        loss_history = []
        for epoch in range(1, epochs + 1):
            Y_pred = self.forward(X)
            loss = self.compute_loss(Y_pred, Y)
            loss_history.append(loss)

            self.backward(Y)
            self.update_parameters(learning_rate)

            if epoch % 1000 == 0:
                learning_rate *= 0.9

            if print_loss and epoch % 1000 == 0:
                print(f"Epoch {epoch}, Loss: {loss}")

        return loss_history

    def predict(self, X):
        return self.forward(X)

"""### 1.3 Funtions to create Mini Batches and do batch training"""

def create_mini_batches(X, Y, batch_size):
    # Shuffle the data at the beginning of each epoch
    m = X.shape[1]  # Number of examples
    permutation = np.random.permutation(m)
    X_shuffled = X[:, permutation]
    Y_shuffled = Y[:, permutation]

    mini_batches = []

    # Create mini-batches
    num_complete_batches = m // batch_size
    for k in range(num_complete_batches):
        X_mini_batch = X_shuffled[:, k * batch_size:(k + 1) * batch_size]
        Y_mini_batch = Y_shuffled[:, k * batch_size:(k + 1) * batch_size]
        mini_batches.append((X_mini_batch, Y_mini_batch))

    # Handle the remaining examples if any
    if m % batch_size != 0:
        X_mini_batch = X_shuffled[:, num_complete_batches * batch_size:]
        Y_mini_batch = Y_shuffled[:, num_complete_batches * batch_size:]
        mini_batches.append((X_mini_batch, Y_mini_batch))

    return mini_batches

def train_with_mini_batches(ann, X, Y, epochs=1000, learning_rate=0.01, batch_size = 64 , print_loss=True):

  print(f"\nTraining with batch size: {batch_size}")
  loss_history = []


  for epoch in range(1, epochs + 1):
      # Create mini-batches
      mini_batches = create_mini_batches(X, Y, batch_size)

      epoch_loss = 0

      for mini_batch_X, mini_batch_Y in mini_batches:
          # Forward and backward pass for each mini-batch
          Y_pred = ann.forward(mini_batch_X)
          loss = ann.compute_loss(Y_pred, mini_batch_Y)
          epoch_loss += loss

          ann.backward(mini_batch_Y)
          ann.update_parameters(learning_rate)

      # Store the loss at the end of each epoch
      loss_history.append(epoch_loss / len(mini_batches))


      if epoch % 1000 == 0:
          learning_rate *= 0.9  # Learning rate decay

      if print_loss and epoch % 100 == 0:
          print(f"Epoch {epoch}, Loss: {epoch_loss / len(mini_batches)}")


  return loss_history

"""### 1.4 Training our ANN utililing Different size batches and activations

Dataset genetation
"""

# Generate the dataset
X = np.linspace(-2 * np.pi, 2 * np.pi, 1000).reshape(1, -1)  # Shape: (1, 1000)
Y = np.sin(X)  # Shape: (1, 1000)

# Validation Data
X_val = np.linspace(-2 * np.pi, 2 * np.pi, 300).reshape(1, -1)  # Shape: (1, 300)
val_y = np.sin(X_val)

"""## 1.5 Training Using `tanh` as activation fucntion with batch sizes [1, 64, 256, 1000]

Function for initalizing the model
"""

def initModelLayers():
  ann = ANN_1()
  # Input layer: 1 node
  # Hidden layers: 2 hidden layers with 10 nodes each using Tanh activation
  # Output layer: 1 node with linear activation
  # Linear activation for output

  ann.add_layer(input_size=1, output_size=15, activation='tanh')
  ann.add_layer(input_size=15, output_size=15, activation='tanh')
  ann.add_layer(input_size=15, output_size=15, activation='tanh')
  ann.add_layer(input_size=15, output_size=15, activation='tanh')
  ann.add_layer(input_size=15, output_size=1, activation='linear')

  return ann

"""Defining Hyperparameters"""

epochs = 500
learning_rate = 0.1

"""##### tanh - batch size 1"""

ann_1 = initModelLayers()
loss_history_1 = train_with_mini_batches(ann_1, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 1, print_loss=True)

"""#### tanh - batch size 64"""

ann_64 = initModelLayers()
loss_history_64 = train_with_mini_batches(ann_64, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 64, print_loss=True)

"""#### tanh - batch size 256"""

ann_256 = initModelLayers()
loss_history_256 = train_with_mini_batches(ann_256, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 256, print_loss=True)

"""#### tanh - batch size 1000"""

ann_1000 = initModelLayers()
loss_history_1000 = train_with_mini_batches(ann_1000, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 1000, print_loss=True)

def LossCurve(loss_history_1, loss_history_2, loss_history_3, loss_history_4):
    plt.figure(figsize=(14, 8))

    # Set main title
    plt.suptitle('Tanh Loss Curve', fontsize=16)

    # First subplot for batch size 1
    plt.subplot(2, 2, 1)  # 2 rows, 2 columns, position 1
    plt.plot(loss_history_1, color='blue')
    plt.title('Batch Size 1')
    plt.xlabel('Epoch')
    plt.ylabel('MSE Loss')
    plt.grid(True)

    # Second subplot for batch size 2 (64)
    plt.subplot(2, 2, 2)  # 2 rows, 2 columns, position 2
    plt.plot(loss_history_2, color='green')
    plt.title('Batch Size 64')
    plt.xlabel('Epoch')
    plt.ylabel('MSE Loss')
    plt.grid(True)

    # Third subplot for batch size 3 (256)
    plt.subplot(2, 2, 3)  # 2 rows, 2 columns, position 3
    plt.plot(loss_history_3, color='orange')
    plt.title('Batch Size 256')
    plt.xlabel('Epoch')
    plt.ylabel('MSE Loss')
    plt.grid(True)

    # Fourth subplot for full batch size
    plt.subplot(2, 2, 4)  # 2 rows, 2 columns, position 4
    plt.plot(loss_history_4, color='red')
    plt.title('Full Batch')
    plt.xlabel('Epoch')
    plt.ylabel('MSE Loss')
    plt.grid(True)

    # Adjust layout to prevent overlapping
    plt.tight_layout(rect=[0, 0, 1, 0.95])  # Leave space for the main title

    # Show the plot
    plt.show()

LossCurve(loss_history_1, loss_history_64, loss_history_256, loss_history_1000)

"""### 1.6 Validating our Model with 300 points of Data for `tanh`"""

Y_pred_1 = ann_1.predict(X_val)
Y_pred_64 = ann_64.predict(X_val)
Y_pred_256 = ann_256.predict(X_val)
Y_pred_1000 = ann_1000.predict(X_val)

def PredCurve(X, Y, X_val, Y_pred_1, Y_pred_2, Y_pred_3, Y_pred_4, title: str):
    plt.figure(figsize=(14, 10))
    plt.suptitle(title, fontsize=16)
    # First subplot for Y_pred_1
    plt.subplot(2, 2, 1)  # 2 rows, 2 columns, position 1
    plt.plot(X.flatten(), Y.flatten(), label='True sin(x)', color='green')
    plt.plot(X_val.flatten(), Y_pred_1.flatten(), label='ANN Output 1', color='red', linestyle='--')
    plt.legend()
    plt.title('Y_pred_1')
    plt.xlabel('x')
    plt.ylabel('sin(x)')
    plt.grid(True)

    # Second subplot for Y_pred_64
    plt.subplot(2, 2, 2)  # 2 rows, 2 columns, position 2
    plt.plot(X.flatten(), Y.flatten(), label='True sin(x)', color='green')
    plt.plot(X_val.flatten(), Y_pred_2.flatten(), label='ANN Output 2', color='blue', linestyle='--')
    plt.legend()
    plt.title('Y_pred_64')
    plt.xlabel('x')
    plt.ylabel('sin(x)')
    plt.grid(True)

    # Third subplot for Y_pred_256
    plt.subplot(2, 2, 3)  # 2 rows, 2 columns, position 3
    plt.plot(X.flatten(), Y.flatten(), label='True sin(x)', color='green')
    plt.plot(X_val.flatten(), Y_pred_3.flatten(), label='ANN Output 3', color='orange', linestyle='--')
    plt.legend()
    plt.title('Y_pred_256')
    plt.xlabel('x')
    plt.ylabel('sin(x)')
    plt.grid(True)

    # Fourth subplot for Y_pred_1000
    plt.subplot(2, 2, 4)  # 2 rows, 2 columns, position 4
    plt.plot(X.flatten(), Y.flatten(), label='True sin(x)', color='green')
    plt.plot(X_val.flatten(), Y_pred_4.flatten(), label='ANN Output 4', color='purple', linestyle='--')
    plt.legend()
    plt.title('Y_pred_1000')
    plt.xlabel('x')
    plt.ylabel('sin(x)')
    plt.grid(True)

    # Adjust layout to fit everything and show plot
    plt.tight_layout(rect=[0, 0, 1, 0.95])  # Leave space for titles if needed
    plt.show()

# Plot the true function vs ANN predictions
PredCurve(X, Y, X_val, Y_pred_1, Y_pred_64, Y_pred_256, Y_pred_1000, 'Tanh Validation Curve')

"""#### MAPE 15 15 15, 0.1, 64"""

def calculate_mape(y_true, y_pred, epsilon=0.001, threshold=0.1):
    # Create a mask for values greater than the threshold
    mask = np.abs(y_true) > threshold
    # Calculate MAPE only for values where y_true is greater than the threshold
    mape = np.mean(np.abs((y_true[mask] - y_pred[mask]) / (y_true[mask] + epsilon))) * 100
    return mape

mape_val = calculate_mape(val_y, Y_pred_64, threshold=0.1)
print(f"Validation MAPE: {mape_val}%")

"""## 1.7 Training Using `ReLU` as activation fucntion with batch sizes [1, 64, 256, 1000]"""

def ReLU_initModelLayers():
  ann = ANN_1()
  # Input layer: 1 node
  # Hidden layers: 2 hidden layers with 10 nodes each using Tanh activation
  # Output layer: 1 node with linear activation
  # Linear activation for output

  ann.add_layer(input_size=1, output_size=10, activation='relu')
  ann.add_layer(input_size=10, output_size=10, activation='relu')
  ann.add_layer(input_size=10, output_size=10, activation='relu')
  ann.add_layer(input_size=10, output_size=1, activation='tanh')

  return ann

epochs=1000

"""##### ReLU - batch size 1"""

ReLU_ann_1 = ReLU_initModelLayers()
ReLU_loss_history_1 = train_with_mini_batches(ReLU_ann_1, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 1, print_loss=True)

"""##### ReLU - batch size 64"""

ReLU_ann_64 = ReLU_initModelLayers()
ReLU_loss_history_64 = train_with_mini_batches(ReLU_ann_64, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 64, print_loss=True)

"""##### ReLU - batch size 256"""

ReLU_ann_256 = ReLU_initModelLayers()
ReLU_loss_history_256 = train_with_mini_batches(ReLU_ann_256, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 256, print_loss=True)

"""##### ReLU - batch size 1000"""

ReLU_ann_1000 = ReLU_initModelLayers()
ReLU_loss_history_1000 = train_with_mini_batches(ReLU_ann_1000, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 1000, print_loss=True)

LossCurve(ReLU_loss_history_1, ReLU_loss_history_64, ReLU_loss_history_256, ReLU_loss_history_1000)

"""### 1.8 Validating our Model with 300 points of Data for `ReLU`"""

ReLU_Y_pred_1 = ReLU_ann_1.predict(X_val)
ReLU_Y_pred_64 = ReLU_ann_64.predict(X_val)
ReLU_Y_pred_256 = ReLU_ann_256.predict(X_val)
ReLU_Y_pred_1000 = ReLU_ann_1000.predict(X_val)

PredCurve(X, Y, X_val, ReLU_Y_pred_1, ReLU_Y_pred_64, ReLU_Y_pred_256, ReLU_Y_pred_1000, 'ReLU Validation Curve')

"""### 1.9 Using Sigmoid"""

def sig_initModelLayers():
  ann = ANN_1()
  # Input layer: 1 node
  # Hidden layers: 2 hidden layers with 10 nodes each using Tanh activation
  # Output layer: 1 node with linear activation
  # Linear activation for output

  ann.add_layer(input_size=1, output_size=10, activation='sigmoid')
  ann.add_layer(input_size=10, output_size=10, activation='sigmoid')
  ann.add_layer(input_size=10, output_size=10, activation='sigmoid')
  ann.add_layer(input_size=10, output_size=1, activation='linear')

  return ann

epochs=1000

sig_ann_1 = sig_initModelLayers()
sig_loss_history_1 = train_with_mini_batches(sig_ann_1, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 1, print_loss=True)

sig_ann_64 = sig_initModelLayers()
sig_loss_history_64 = train_with_mini_batches(sig_ann_64, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 64, print_loss=True)

sig_ann_256 = sig_initModelLayers()
sig_loss_history_256 = train_with_mini_batches(sig_ann_256, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 256, print_loss=True)

sig_ann_1000 = sig_initModelLayers()
sig_loss_history_1000 = train_with_mini_batches(sig_ann_1000, X, Y, epochs=epochs, learning_rate=learning_rate, batch_size = 1000, print_loss=True)

LossCurve(sig_loss_history_1, sig_loss_history_64, sig_loss_history_256, sig_loss_history_1000)

sig_Y_pred_1 = sig_ann_1.predict(X_val)
sig_Y_pred_64 = sig_ann_64.predict(X_val)
sig_Y_pred_256 = sig_ann_256.predict(X_val)
sig_Y_pred_1000 = sig_ann_1000.predict(X_val)

PredCurve(X, Y, X_val, sig_Y_pred_1, sig_Y_pred_64, sig_Y_pred_256, sig_Y_pred_1000, 'Sigmoid Validation Curve')